site_name: Dex Dev Blog
site_url: https://huningd.github.io/dev-blog/
theme:
  name: material
  language: en
  features:
    - navigation.indexes
  palette:
    - scheme: default
      primary: grey
      accent: grey
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: grey
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
extra_css:
  - styles/custom.css
plugins:
  - search
  - blog:
      blog_toc: true
  - rss:
      match_path: "blog/.*"